[default.extend-words]
indexs = "indices"      # Both are valid, just pick one.
Stichting = "Stichting" # This is Dutch for "Foundation". From DuckDB.
FPR = "FPR"             # False Positive Rate
inout = "inout"         # This is a SQL keyword!
numer = "numer"         # numerator
nd = "nd"               # N-dimentional / 2nd
steam = "stream"        # You played with Steam games too much.
# Some weird short variable names
ot = "ot"
bui = "bui"

[default.extend-identifiers]

[files]
extend-exclude = [
    "src/tests/regress/data",
    "e2e_test",
    "**/*.svg",
    "scripts",
    "src/frontend/planner_test/tests/testdata",
    "src/tests/sqlsmith/tests/freeze",
    "src/workspace-hack/Cargo.toml",
    "**/go.mod",
    "**/go.sum",
]
