---
version: "3"
services:
  compactor-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: compactor-0
  compute-node-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: compute-node-0
  etcd-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: etcd-0
  frontend-node-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: frontend-node-0
  grafana-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: grafana-0
  meta-node-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: meta-node-0
  minio-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: minio-0
  prometheus-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: prometheus-0
  message_queue:
    extends:
      file: ../../docker/docker-compose.yml
      service: message_queue

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=myuser --dbname=mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "wal_level=logical" ]
    restart: always
    container_name: postgres

  mysql:
    image: mysql
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=mysql
     - MYSQL_USER=myuser
     - MYSQL_PASSWORD=123456
     - MYSQL_DATABASE=mydb
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p123456" ]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: mysql
    
  flink-jobmanager:
    image: flink
    build: ./flink
    ports:
      - "8082:8081" # 8081 is used by message_queue
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager        
    container_name: flink-jobmanager

  flink-taskmanager:
    image: flink
    build: ./flink
    depends_on:
      - flink-jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
    container_name: flink-taskmanager

  flink-sql-client:
    image: flink
    build: ./flink
    command: bin/sql-client.sh
    depends_on:
      - flink-jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        rest.address: flink-jobmanager        
    container_name: flink-sql-client

  connect:
    image: debezium/connect:2.2
    build:
      context: debezium-jdbc
      args:
        DEBEZIUM_VERSION: 2.2
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - message_queue
    environment:
     - BOOTSTRAP_SERVERS=message_queue:29092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    container_name: connect

volumes:
  compute-node-0:
    external: false
  etcd-0:
    external: false
  grafana-0:
    external: false
  minio-0:
    external: false
  prometheus-0:
    external: false
  message_queue:
    external: false
name: risingwave-compose
